#!/bin/bash

# Name of the docker image
#image_name="<dockerhub-name>/template"

# Run tests (if any)
# poetry run pytest

# Run cz bump with poetry
poetry run cz bump --yes

# If cz bump fails, unstash changes and exit with an error code
if [ $? -ne 0 ]; then
  echo "cz bump failed, cancelling commit"
  git stash pop -q
  exit $?
fi

# Add changes to the commit if the version was bumped
if git diff --name-only | grep -q 'VERSION\|pyproject.toml'; then
  echo "Version has been bumped, adding changes to the commit..."
  git add -u :/
  git commit --amend --no-edit
fi

# Check if image_name variable is set
if [ -n "$image_name" ]; then
  # Dockerfile location
  dockerfile_path=".devcontainer/Dockerfile"

  # Building docker image
  echo "Building Docker image from Dockerfile at $dockerfile_path..."
  # Uncomment below line to enable docker build
  # docker build -t $image_name -f $dockerfile_path .

  # Pushing to Docker Hub
  echo "Pushing Docker image to Docker Hub..."
  # Uncomment below line to enable docker push
  # docker push $image_name

  # If Docker build or push fail, stop the push
  if [ $? -ne 0 ]; then
    echo "Docker build or push failed, cancelling git push"
    exit 1
  fi
fi
